#!/bin/sh
### BEGIN INIT INFO
# Provides:          maildev
# Required-Start:    $local_fs $network $named $time $syslog
# Required-Stop:     $local_fs $network $named $time $syslog
# Default-Start:     2 3 4 5
# Default-Stop:      0 1 6
# Description:       Daemon Script for maildev
### END INIT INFO
 
SCRIPT=maildev
RUNAS=vagrant
 
PIDFILE=/var/run/maildev.pid
LOGFILE=/var/log/maildev.log
 
start() {
  if [ -f /var/run/$PIDNAME ] && kill -0 $(cat /var/run/$PIDNAME); then
    echo 'Service already running' >&2
    return 1
  fi
  echo 'Starting service…' >&2
  local CMD="$SCRIPT &> \"$LOGFILE\" & echo \$!"
  su -c "$CMD" $RUNAS > "$PIDFILE"
  echo 'Service started' >&2
}
 
stop() {
  if [ ! -f "$PIDFILE" ] || ! kill -0 $(cat "$PIDFILE"); then
    echo 'Service not running' >&2
    return 1
  fi
  echo 'Stopping service…' >&2
  kill -15 $(cat "$PIDFILE") && rm -f "$PIDFILE"
  echo 'Service stopped' >&2
}

status () {
 if [ -f $PIDFILE ] && kill -0 $(cat $PIDFILE); then
    PID=$(cat "$PIDFILE")
    echo "maildev is running (pid $PID)"
    exit 0
 else 
    echo 'Not Running' >&2
    exit 1
 fi
}



case "$1" in
  start)
    start
    ;;
  stop)
    stop
    ;;
  restart)
    stop
    start
    ;;
  status)
    status
    ;;
  *)
    echo "Usage: $0 {start|stop|restart|status}"
esac